// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Datos;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20230920024601_AgregandoDatosAlaTablaVilla")]
    partial class AgregandoDatosAlaTablaVilla
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Detalles de la Villa....",
                            FechaActualizacion = new DateTime(2023, 9, 20, 4, 46, 1, 410, DateTimeKind.Local).AddTicks(2305),
                            FechaCreacion = new DateTime(2023, 9, 20, 4, 46, 1, 410, DateTimeKind.Local).AddTicks(2255),
                            ImageUrl = "",
                            MetrosCuadrados = 10,
                            Nombre = "VillaReal",
                            Ocupantes = 10,
                            Tarifa = 25.43
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Detalles de la Villa2....",
                            FechaActualizacion = new DateTime(2023, 9, 20, 4, 46, 1, 410, DateTimeKind.Local).AddTicks(2322),
                            FechaCreacion = new DateTime(2023, 9, 20, 4, 46, 1, 410, DateTimeKind.Local).AddTicks(2316),
                            ImageUrl = "",
                            MetrosCuadrados = 20,
                            Nombre = "VillaReal2",
                            Ocupantes = 20,
                            Tarifa = 60.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
